name: Update Kommit Manifest

on:
  repository_dispatch:
    types: [update-kommit]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Get latest commit message from Kommit repo
        id: get_commit_message
        run: |
          latest_commit_message=$(curl -s https://api.github.com/repos/OmyDaGreat/Kommit/commits/main | jq -r '.commit.message')
          echo "COMMIT_MESSAGE=$latest_commit_message" >> $GITHUB_ENV
      - name: Update manifest
        run: |
          mkdir -p bucket
          cat > bucket/kommit.json << EOF
          {
              "version": "${{ github.event.client_payload.version }}",
              "description": "A Kotlin-based conventional commit message generator",
              "homepage": "https://github.com/OmyDaGreat/Kommit",
              "license": "MIT",
              "architecture": {
                  "64bit": {
                      "url": "https://github.com/OmyDaGreat/Kommit/releases/download/${{ github.event.client_payload.tag }}/kommit-${{ github.event.client_payload.version }}.zip",
                      "hash": "${{ github.event.client_payload.sha256 }}"
                  }
              },
              "bin": "kommit.bat",
              "persist": ".kommit.yaml",
              "checkver": "github",
              "autoupdate": {
                  "architecture": {
                      "64bit": {
                          "url": "https://github.com/OmyDaGreat/Kommit/releases/download/v\$version/kommit-\$version.zip"
                      }
                  }
              }
          }
          EOF
      - name: Commit and push
        run: |
          git add bucket/kommit.json
          git commit -m "$COMMIT_MESSAGE"
          git push
