name: Update Kommit Manifest

on:
  repository_dispatch:
    types: [update-kommit]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update manifest
        run: |
          mkdir -p bucket
          cat > bucket/kommit.json << EOF
          {
              "version": "${{ github.event.client_payload.version }}",
              "description": "A Kotlin-based conventional commit message generator",
              "homepage": "https://github.com/OmyDaGreat/Kommit",
              "license": "MIT",
              "architecture": {
                  "64bit": {
                      "url": "https://github.com/OmyDaGreat/Kommit/releases/download/${{ github.event.client_payload.tag }}/kommit-${{ github.event.client_payload.version }}.zip",
                      "hash": "${{ github.event.client_payload.sha256 }}"
                  }
              },
              "bin": "kommit.bat",
              "persist": "kommit.yml",
              "checkver": "github",
              "autoupdate": {
                  "architecture": {
                      "64bit": {
                          "url": "https://github.com/OmyDaGreat/Kommit/releases/download/v\$version/kommit-\$version.zip"
                      }
                  }
              }
          }
          EOF
          
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bucket/kommit.json
          git commit -m "Update kommit to version ${{ github.event.client_payload.version }}"
          git push
